# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2dbda55f02d6ad4486b4e350888bc947e817cb96b5e6775b6812b7a582606dd946ba198633c334bdc5eea3bc57dbb6c419fa29142f910c9414a027327688e6a0

test:
  secret_key_base: 60b27d9768e7665500dd90f758c5526c7c5e841736322a9d3bff8ae933f7b501cdb9920a8e80d749487a5b79f01f7ed7f7a56560f23dab96aed232a12e319df7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
